[package]
name = "mandelbrot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.4.3"
image = "0.25.5"
rayon = "1.10.0"
ocl = "0.19.7"
anyhow = "1.0.97"
clap = { version = "4.5.32", features = ["derive"] }
